version: '3.1'
services:
  cas:
    build: .
    ports:
     - "8443:8443"

  varnish:
    image: eeacms/varnish
    volumes:
      - ./varnish.vcl:/etc/varnish/conf.d/varnish.vcl:ro
    ports:
      - "80:6081"
    depends_on:
      - proxy

  proxy:
    image: nginx:1.15.12-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80
      
  servicio:
    image: tomcat:9.0.12-jre8
    volumes:
      - ./servicio:/usr/local/tomcat/webapps
      - ./etc/cas/cacerts:/docker-java-home/jre/lib/security/cacerts
    ports:
      - 8080

  public:
    image: tomcat:9.0.12-jre8
    volumes:
      - ./public:/usr/local/tomcat/webapps
      - ./etc/cas/cacerts:/docker-java-home/jre/lib/security/cacerts
    ports:
      - 8080

  liferay:
    image: liferay/portal:7.1.0-ga1-201809012030
    volumes:
      - ./etc/cas/cacerts:/usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts
    environment:
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_PROTOCOL=http
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_HTTP_PERIOD_PORT=80
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_HTTPS_PERIOD_PORT=443
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_HOST=localhost
      #- LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_HOST_PERIOD_ENABLED=true
      #- LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PORT_PERIOD_ENABLED=true
      #- LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PROTOCOL_PERIOD_ENABLED=true
    ports:
      - 8080
