version: '3.1'
services:
  cas:
    build: .
    ports:
     - "8443:8443"

  varnish:
    image: eeacms/varnish
    volumes:
      - ./varnish.vcl:/etc/varnish/conf.d/varnish.vcl:ro
    ports:
      - "80:6081"
    depends_on:
      - proxy

  proxy:
    image: nginx:1.15.12-alpine
    volumes:
      - ./pub-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80
      
  servicio:
    image: tomcat:9.0.12-jre8
    volumes:
      - ./servicio:/usr/local/tomcat/webapps
      - ./etc/cas/cacerts:/docker-java-home/jre/lib/security/cacerts
    ports:
      - 8080

  public:
    image: tomcat:9.0.12-jre8
    volumes:
      - ./public:/usr/local/tomcat/webapps
      - ./etc/cas/cacerts:/docker-java-home/jre/lib/security/cacerts
    ports:
      - 8080:8080
